# Dashboard for issuing queries to the SparkifyDB
make sure that you have run `python create_tables.py` and `python etl.py` to populate the database before continuing

In [1]:
%load_ext sql

In [2]:
%sql postgresql://student:student@127.0.0.1/sparkifydb

'Connected: student@sparkifydb'

In [3]:
%%sql 

SELECT users.user_id, users.first_name, users.last_name, users.level, Count(*) as num_listens
FROM songplays
JOIN users ON songplays.user_id = users.user_id
GROUP BY users.user_id, users.first_name, users.level
ORDER BY num_listens DESC
LIMIT 100

 * postgresql://student:***@127.0.0.1/sparkifydb
96 rows affected.

[(49, 'Chloe', 'Cuevas', 'paid', 689),
 (80, 'Tegan', 'Levine', 'paid', 665),
 (97, 'Kate', 'Harrell', 'paid', 557),
 (15, 'Lily', 'Koch', 'paid', 463),
 (44, 'Aleena', 'Kirby', 'paid', 397),
 (29, 'Jacqueline', 'Lynch', 'paid', 346),
 (24, 'Layla', 'Griffin', 'paid', 321),
 (73, 'Jacob', 'Klein', 'paid', 289),
 (88, 'Mohammad', 'Rodriguez', 'paid', 270),
 (36, 'Matthew', 'Jones', 'paid', 248),
 (16, 'Rylan', 'George', 'paid', 223),
 (95, 'Sara', 'Johnson', 'paid', 213),
 (85, 'Kinsley', 'Young', 'paid', 179),
 (30, 'Avery', 'Watkins', 'paid', 178),
 (25, 'Jayden', 'Graves', 'paid', 169),
 (42, 'Harper', 'Barrett', 'paid', 140),
 (58, 'Emily', 'Benson', 'paid', 140),
 (26, 'Ryan', 'Smith', 'free', 114),
 (82, 'Avery', 'Martinez', 'paid', 87),
 (72, 'Hayden', 'Brock', 'paid', 72),
 (32, 'Lily', 'Burns', 'free', 56),
 (101, 'Jayden', 'Fox', 'free', 55),
 (50, 'Ava', 'Robinson', 'free', 48),
 (86, 'Aiden', 'Hess', 'free', 45),
 (66, 'Kevin', 'Arellano', 'free', 37),
 (37, 'Jordan', 'Hicks', 'free', 34),
 (70, 'Jaleah', 'Hayes', 'paid', 33),
 (69, 'Anabelle', 'Simpson', 'free', 29),
 (10, 'Sylvie', 'Cruz', 'free', 28),
 (83, 'Stefany', 'White', 'free', 27),
 (54, 'Kaleb', 'Cook', 'free', 27),
 (92, 'Ryann', 'Smith', 'free', 27),
 (8, 'Kaylee', 'Summers', 'free', 27),
 (67, 'Colm', 'Santana', 'free', 25),
 (61, 'Samuel', 'Gonzalez', 'free', 24),
 (6, 'Cecilia', 'Owens', 'free', 23),
 (14, 'Theodore', 'Harris', 'free', 22),
 (63, 'Ayla', 'Johnson', 'free', 20),
 (53, 'Celeste', 'Williams', 'free', 20),
 (33, 'Bronson', 'Harris', 'free', 20),
 (100, 'Adler', 'Barrera', 'free', 19),
 (75, 'Joseph', 'Gutierrez', 'free', 18),
 (60, 'Devin', 'Larson', 'free', 18),
 (52, 'Theodore', 'Smith', 'free', 17),
 (65, 'Amiya', 'Davidson', 'paid', 17),
 (35, 'Molly', 'Taylor', 'free', 16),
 (9, 'Wyatt', 'Scott', 'free', 16),
 (55, 'Martin', 'Johnson', 'free', 15),
 (51, 'Maia', 'Burke', 'free', 15),
 (76, 'Jayden', 'Duffy', 'free', 14),
 (78, 'Chloe', 'Roth', 'free', 14),
 (96, 'Cierra', 'Finley', 'free', 13),
 (12, 'Austin', 'Rosales', 'free', 12),
 (43, 'Jahiem', 'Miles', 'free', 11),
 (62, 'Connar', 'Moreno', 'free', 10),
 (2, 'Jizelle', 'Benjamin', 'free', 10),
 (77, 'Magdalene', 'Herman', 'free', 10),
 (89, 'Kynnedi', 'Sanchez', 'free', 10),
 (20, 'Aiden', 'Ramirez', 'paid', 9),
 (91, 'Jayden', 'Bell', 'free', 9),
 (34, 'Evelin', 'Ayala', 'free', 9),
 (41, 'Brayden', 'Clark', 'free', 9),
 (19, 'Zachary', 'Thomas', 'free', 9),
 (57, 'Katherine', 'Gay', 'free', 8),
 (74, 'Braden', 'Parker', 'free', 8),
 (94, 'Noah', 'Chavez', 'free', 7),
 (17, 'Makinley', 'Jones', 'free', 7),
 (28, 'Brantley', 'West', 'free', 7),
 (40, 'Tucker', 'Garrison', 'free', 7),
 (81, 'Sienna', 'Colon', 'free', 6),
 (84, 'Shakira', 'Hunt', 'free', 6),
 (71, 'Ayleen', 'Wise', 'free', 5),
 (18, 'Jacob', 'Rogers', 'free', 5),
 (13, 'Ava', 'Robinson', 'free', 5),
 (4, 'Alivia', 'Terrell', 'free', 5),
 (7, 'Adelyn', 'Jordan', 'free', 5),
 (99, 'Ann', 'Banks', 'free', 4),
 (5, 'Elijah', 'Davis', 'free', 4),
 (23, 'Morris', 'Gilmore', 'free', 4),
 (98, 'Jordyn', 'Powell', 'free', 4),
 (48, 'Marina', 'Sutton', 'free', 3),
 (3, 'Isaac', 'Valdez', 'free', 3),
 (90, 'Andrea', 'Butler', 'free', 3),
 (47, 'Kimber', 'Norris', 'free', 3),
 (68, 'Jordan', 'Rodriguez', 'free', 3),
 (38, 'Gianna', 'Jones', 'free', 3),
 (39, 'Walter', 'Frye', 'free', 2),
 (56, 'Cienna', 'Freeman', 'free', 2),
 (22, 'Sean', 'Wilson', 'free', 2),
 (27, 'Carlos', 'Carter', 'free', 2),
 (64, 'Hannah', 'Calhoun', 'free', 2),
 (59, 'Lily', 'Cooper', 'free', 2),
 (79, 'James', 'Martin', 'free', 2),
 (11, 'Christian', 'Porter', 'free', 2),
 (87, 'Dustin', 'Lee', 'free', 1),
 (45, 'Dominick', 'Norris', 'free', 1)]